version: '3'
services:
  neo4j:
    image: neo4j:4.3.6
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
    environment:
      - NEO4J_AUTH=neo4j/admin
  spring-boot:
    build: ./Dockerfile
    image: spring-boot:latest
    container_name: spring-boot
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=bolt://neo4j:7687
      - SPRING_DATASOURCE_USERNAME=neo4j
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - neo4j
