FROM openjdk:17-jdk-slim
RUN apt-get update && apt-get install -y git maven
RUN git clone https://github.com/vicato2000/socialB.git /app/socialB
WORKDIR /app/socialB
RUN ls
RUN mvn package
#CMD ["java", "-jar", "/app/socialB/target/socialB-0.0.1-SNAPSHOT.jar"]

