version: '3'
services:
  neo4j:
    image: neo4j:4.3.6
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
  spring-boot:
    build:
      context: .
      dockerfile: DockerFile
    container_name: spring-boot
    ports:
      - "8080:8080"
    environment:
      - DB_URL=neo4j
      - DB_PORT=7687
      - SPRING_DATASOURCE_USERNAME=neo4j
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - neo4j
